;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2024 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-2137-ACAB-99                      |
; |                                                                         |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 9846E486CF47266298C3A2C70CFA6CA139450C446D2E05BD2E6C190387B7A457
; Input MD5    : C2433BD83BA24B411CCC50E15CFEC665
; Input CRC32  : 5649334D
; Compiler     : Visual C++ (guessed)

; File Name   : C:\Users\kvthw\Flux\helloworld.exe
; Format      : Portable executable for AMD64 (PE)
; Imagebase   : 140000000
; Timestamp   : 695824C3 (Fri Jan 02 20:04:19 2026)
; Section 1. (virtual address 00001000)
; Virtual size                  : 000001D8 (    472.)
; Section size in file          : 00000200 (    512.)
; Offset to raw data for section: 00000200
; Flags 60000020: Text Executable Readable
; Alignment     : default

.686p
.mmx
.model flat


; Segment type: Pure code
; Segment permissions: Read/Execute
_text segment para public 'CODE' use64
assume cs:_text
;org 140001000h
assume es:nothing, ss:nothing, ds:_text, fs:nothing, gs:nothing



; __int64 __fastcall sub_140001000(LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite)
sub_140001000 proc near

lpOverlapped= qword ptr -18h

push    rsi
push    rdi
mov     esi, edx
mov     rdi, rcx
mov     rcx, 0FFFFFFFFFFFFFFF5h ; nStdHandle
sub     rsp, 20h
call    GetStdHandle
add     rsp, 20h
mov     rcx, rax        ; hFile
mov     rdx, rdi        ; lpBuffer
mov     r8d, esi        ; nNumberOfBytesToWrite
xor     r9, r9          ; lpNumberOfBytesWritten
sub     rsp, 28h
mov     [rsp+38h+lpOverlapped], r9 ; lpOverlapped
call    WriteFile
add     rsp, 28h
pop     rdi
pop     rsi
retn
sub_140001000 endp

algn_14000103C:
align 20h



sub_140001040 proc near

lpOverlapped= qword ptr -18h

push    rsi
push    rdi
lea     rsi, byte_140001128
mov     edi, 1
mov     rcx, 0FFFFFFFFFFFFFFF5h ; nStdHandle
sub     rsp, 20h
call    GetStdHandle
add     rsp, 20h
mov     rcx, rax        ; hFile
mov     rdx, rsi        ; lpBuffer
mov     r8d, edi        ; nNumberOfBytesToWrite
xor     r9, r9          ; lpNumberOfBytesWritten
sub     rsp, 28h
mov     [rsp+38h+lpOverlapped], r9 ; lpOverlapped
call    WriteFile
add     rsp, 28h
pop     rdi
pop     rsi
retn
sub_140001040 endp

algn_140001083:
align 10h
; [00000001 BYTES: COLLAPSED FUNCTION nullsub_1. PRESS CTRL-NUMPAD+ TO EXPAND]
align 20h
; [00000001 BYTES: COLLAPSED FUNCTION nullsub_2. PRESS CTRL-NUMPAD+ TO EXPAND]
align 10h
; [00000001 BYTES: COLLAPSED FUNCTION nullsub_3. PRESS CTRL-NUMPAD+ TO EXPAND]
align 20h



public start
start proc near

lpOverlapped= qword ptr -18h

push    rsi
push    rdi
lea     rsi, byte_1400011B1
mov     edi, 0Ch
mov     rcx, 0FFFFFFFFFFFFFFF5h ; nStdHandle
sub     rsp, 20h
call    GetStdHandle
add     rsp, 20h
mov     rcx, rax        ; hFile
mov     rdx, rsi        ; lpBuffer
mov     r8d, edi        ; nNumberOfBytesToWrite
xor     r9, r9          ; lpNumberOfBytesWritten
sub     rsp, 28h
mov     [rsp+38h+lpOverlapped], r9 ; lpOverlapped
call    WriteFile
add     rsp, 28h
xor     eax, eax
pop     rdi
pop     rsi
retn
start endp

algn_140001105:
align 10h
; [00000006 BYTES: COLLAPSED FUNCTION GetStdHandle. PRESS CTRL-NUMPAD+ TO EXPAND]
align 20h
; [00000006 BYTES: COLLAPSED FUNCTION WriteFile. PRESS CTRL-NUMPAD+ TO EXPAND]
align 8
byte_140001128 db 0Ah, 3 dup(0CCh)
__IMPORT_DESCRIPTOR_KERNEL32 dd rva off_140001158 ; Import Name Table
dd 0                    ; Time stamp
dd 0                    ; Forwarder Chain
dd rva aKernel32Dll     ; DLL Name
dd rva __imp_GetStdHandle ; Import Address Table
dq 2 dup(0)
dq 0CCCCCCCC00000000h
;
; Import names for KERNEL32.dll
;
off_140001158 dq rva word_140001188
dq rva word_140001198
dq 0
_text ends

;
; Imports from KERNEL32.dll
;

; Segment type: Externs
; _idata
; HANDLE (__stdcall *GetStdHandle)(DWORD nStdHandle)
extrn __imp_GetStdHandle:qword
; BOOL (__stdcall *WriteFile)(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped)
extrn __imp_WriteFile:qword



; Segment type: Pure code
; Segment permissions: Read/Execute
_text segment para public 'CODE' use64
assume cs:_text
;org 140001188h
assume es:nothing, ss:nothing, ds:_text, fs:nothing, gs:nothing
word_140001188 dw 302h
db 'GetStdHandle',0
align 8
word_140001198 dw 65Fh
db 'WriteFile',0
aKernel32Dll db 'KERNEL32.dll',0
byte_1400011B1 db 48h, 65h, 2 dup(6Ch), 6Fh, 20h, 57h
dq 0CCCCCC21646C726Fh
stru_1400011C0 UNWIND_INFO_HDR <1, 0, 2, 2, 0, 0>
UNWIND_CODE <2, 0, 7>   ; UWOP_PUSH_NONVOL
UNWIND_CODE <1, 0, 6>   ; UWOP_PUSH_NONVOL
stru_1400011C8 UNWIND_INFO_HDR <1, 0, 2, 2, 0, 0>
UNWIND_CODE <2, 0, 7>   ; UWOP_PUSH_NONVOL
UNWIND_CODE <1, 0, 6>   ; UWOP_PUSH_NONVOL
stru_1400011D0 UNWIND_INFO_HDR <1, 0, 2, 2, 0, 0>
UNWIND_CODE <2, 0, 7>   ; UWOP_PUSH_NONVOL
UNWIND_CODE <1, 0, 6>   ; UWOP_PUSH_NONVOL
align 40h
dq 1C0h dup(?)
_text ends

; Section 2. (virtual address 00002000)
; Virtual size                  : 00000024 (     36.)
; Section size in file          : 00000200 (    512.)
; Offset to raw data for section: 00000400
; Flags 40000040: Data Readable
; Alignment     : default

; Segment type: Pure data
; Segment permissions: Read
_pdata segment para public 'DATA' use64
assume cs:_pdata
;org 140002000h
ExceptionDir RUNTIME_FUNCTION <rva sub_140001000, \
                  rva algn_14000103C, \
                  rva stru_1400011C0>
RUNTIME_FUNCTION <rva sub_140001040, \
                  rva algn_140001083, \
                  rva stru_1400011C8>
RUNTIME_FUNCTION <rva start, \
                  rva algn_140001105, \
                  rva stru_1400011D0>
align 1000h
_pdata ends


end start
