;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2024 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-2137-ACAB-99                      |
; |                                                                         |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : E3771136CE681E531067D61A467127848B7CD36BD4C235EF9510CB8A356E8AB1
; Input MD5    : 6B04EDB25BBE47CF487DB04C5826691F
; Input CRC32  : 8DC8FFE1
; Compiler     : Visual C++ (guessed)


.686p
.mmx
.model flat


; [000001F8 BYTES: COLLAPSED SEGMENT HEADER. PRESS CTRL-NUMPAD+ TO EXPAND]
; Section 1. (virtual address 000001F8)
; Virtual size                  : 00000108 (    264.)
; Section size in file          : 00000108 (    264.)
; Offset to raw data for section: 000001F8
; Flags 60000020: Text Executable Readable
; Alignment     : default

; Segment type: Pure code
; Segment permissions: Read/Execute
_text segment para public 'CODE' use64
assume cs:_text
;org 1400001F8h
assume es:GAP, ss:GAP, ds:HEADER, fs:nothing, gs:nothing



public start
start proc near

lpOverlapped= qword ptr -28h
var_20= qword ptr -20h
var_18= dword ptr -18h

push    rsi
push    rdi
sub     rsp, 10h
mov     rax, 6F57206F6C6C6548h
mov     [rsp+20h+var_20], rax
mov     [rsp+20h+var_18], 21646C72h
mov     rsi, rsp
xor     edi, edi
mov     rcx, 0FFFFFFFFFFFFFFF5h ; nStdHandle
sub     rsp, 20h
call    GetStdHandle
add     rsp, 20h
mov     rcx, rax        ; hFile
mov     rdx, rsi        ; lpBuffer
mov     r8d, edi        ; nNumberOfBytesToWrite
xor     r9, r9          ; lpNumberOfBytesWritten
sub     rsp, 28h
mov     [rsp+48h+lpOverlapped], r9 ; lpOverlapped
call    WriteFile
add     rsp, 28h
xor     eax, eax
add     rsp, 10h
pop     rdi
pop     rsi
retn
start endp

algn_140000254:
align 8
; [00000006 BYTES: COLLAPSED FUNCTION GetStdHandle. PRESS CTRL-NUMPAD+ TO EXPAND]
db 0Ah dup(0CCh)
; [00000006 BYTES: COLLAPSED FUNCTION WriteFile. PRESS CTRL-NUMPAD+ TO EXPAND]
align 10h
__IMPORT_DESCRIPTOR_KERNEL32 dd rva off_140000298 ; Import Name Table
dd 0                    ; Time stamp
dd 0                    ; Forwarder Chain
dd rva aKernel32Dll     ; DLL Name
dd rva __imp_GetStdHandle ; Import Address Table
align 8
dq 2 dup(0)
;
; Import names for KERNEL32.dll
;
off_140000298 dq rva word_1400002C8
dq rva word_1400002D8
dq 0
_text ends

;
; Imports from KERNEL32.dll
;

; Segment type: Externs
; _idata
; HANDLE (__stdcall *GetStdHandle)(DWORD nStdHandle)
extrn __imp_GetStdHandle:qword
; BOOL (__stdcall *WriteFile)(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped)
extrn __imp_WriteFile:qword



; Segment type: Pure code
; Segment permissions: Read/Execute
_text segment para public 'CODE' use64
assume cs:_text
;org 1400002C8h
assume es:GAP, ss:GAP, ds:HEADER, fs:nothing, gs:nothing
word_1400002C8 dw 302h
db 'GetStdHandle',0
align 8
word_1400002D8 dw 65Fh
db 'WriteFile',0
aKernel32Dll db 'KERNEL32.dll',0
align 4
stru_1400002F4 UNWIND_INFO_HDR <1, 0, 6, 3, 0, 0>
UNWIND_CODE <6, 2, 1>   ; UWOP_ALLOC_SMALL
UNWIND_CODE <2, 0, 7>   ; UWOP_PUSH_NONVOL
UNWIND_CODE <1, 0, 6>   ; UWOP_PUSH_NONVOL
align 4
_text ends

; Section 2. (virtual address 00000300)
; Virtual size                  : 0000000C (     12.)
; Section size in file          : 0000000C (     12.)
; Offset to raw data for section: 00000300
; Flags 40000040: Data Readable
; Alignment     : default

; Segment type: Pure data
; Segment permissions: Read
_pdata segment para public 'DATA' use64
assume cs:_pdata
;org 140000300h
ExceptionDir RUNTIME_FUNCTION <rva start, \
                  rva algn_140000254, \
                  rva stru_1400002F4>
_pdata ends


; Segment type: Pure data
; Segment permissions: Read/Write
GAP segment byte private 'DATA' use64
assume cs:GAP
;org 14000030Ch
align 1000h
GAP ends


end start
