;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2024 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-2137-ACAB-99                      |
; |                                                                         |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 218632F1C6B151026F1D1DAB788CE47077C67CB0878071E9E2B816EDEE60B888
; Input MD5    : 7A364A65312A3BA358BA0B9316FD21D9
; Input CRC32  : 3F85B079
; Compiler     : Visual C++ (guessed)


.686p
.mmx
.model flat

_text segment para public 'CODE' use64
assume cs:_text
assume es:GAP, ss:GAP, ds:HEADER, fs:nothing, gs:nothing
db 66h, 2Eh, 0Fh, 1Fh, 84h, 5 dup(0)
align 8



public start
start proc near

var_5= byte ptr -5
var_4= dword ptr -4

push    rax
mov     [rsp+8+var_4], 41h ; 'A'
mov     [rsp+8+var_5], 41h ; 'A'
xor     eax, eax
pop     rcx
retn
start endp

algn_14000021A:
align 4
dd 0CCCCCC0Ah
db 8 dup(0CCh)
dq 100000020h, 2000000000h, 20h, 0
dq 100000020h, 2000000000h
db 20h, 3 dup(0)
stru_14000025C UNWIND_INFO_HDR <1, 0, 1, 1, 0, 0>
UNWIND_CODE <1, 2, 0>   ; UWOP_ALLOC_SMALL
align 4
_text ends

_pdata segment para public 'DATA' use64
assume cs:_pdata
ExceptionDir RUNTIME_FUNCTION <rva start, rva algn_14000021A, rva stru_14000025C>
_pdata ends

GAP segment byte private 'DATA' use64
assume cs:GAP
align 1000h
GAP ends


end start
