;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2024 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-2137-ACAB-99                      |
; |                                                                         |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 6B7BBE88EB67641150674D6795A360B9573AFDBE83E839A5C854FC7E222C97F4
; Input MD5    : 354B4A76AD9B8910D1F1D355CCFD5CA1
; Input CRC32  : 53393FFB
; Compiler     : Visual C++ (guessed)


.686p
.mmx
.model flat


; [000001F8 BYTES: COLLAPSED SEGMENT HEADER. PRESS CTRL-NUMPAD+ TO EXPAND]
; Section 1. (virtual address 000001F8)
; Virtual size                  : 00000048 (     72.)
; Section size in file          : 00000048 (     72.)
; Offset to raw data for section: 000001F8
; Flags 60000020: Text Executable Readable
; Alignment     : default

; Segment type: Pure code
; Segment permissions: Read/Execute
_text segment para public 'CODE' use64
assume cs:_text
;org 1400001F8h
assume es:GAP, ss:GAP, ds:HEADER, fs:nothing, gs:nothing



public start
start proc near

var_8= qword ptr -8

push    rax
mov     rax, 4200000041h
mov     [rsp+8+var_8], rax
xor     eax, eax
pop     rcx
retn
start endp

algn_14000020B:
align 4
dd 0CCCCCC0Ah
db 8 dup(0CCh)
dq 200000040h, 2000000000h, 2 dup(2000000020h)
stru_140000238 UNWIND_INFO_HDR <1, 0, 1, 1, 0, 0>
UNWIND_CODE <1, 2, 0>   ; UWOP_ALLOC_SMALL
align 4
_text ends

; Section 2. (virtual address 00000240)
; Virtual size                  : 0000000C (     12.)
; Section size in file          : 0000000C (     12.)
; Offset to raw data for section: 00000240
; Flags 40000040: Data Readable
; Alignment     : default

; Segment type: Pure data
; Segment permissions: Read
_pdata segment para public 'DATA' use64
assume cs:_pdata
;org 140000240h
ExceptionDir RUNTIME_FUNCTION <rva start, \
                  rva algn_14000020B, \
                  rva stru_140000238>
_pdata ends


; Segment type: Pure data
; Segment permissions: Read/Write
GAP segment byte private 'DATA' use64
assume cs:GAP
;org 14000024Ch
align 1000h
GAP ends


end start
