// test-pack.fx - A Flux package called test-pack
// Generated by fpm create

#import "standard.fx";

using standard::io::console;

namespace test_pack
{
    // TODO: implement your package here
    def main() -> int
    {
        print("Hello from test-pack!\0");
        return 0;
    };

};
